# a custom Docker Image with this Dockerfile
FROM node:14-alpine

# A directory within the virtualized Docker environment
WORKDIR /app

# Copies package.json and package-lock.json to Docker environment
COPY ["yarn.lock", "package.json", "./"]

# Installs all node packages
RUN yarn install

# Copies everything over to Docker environment
COPY . .

# Uses port which is used by the actual application
EXPOSE 5000

# Finally runs the application
CMD [ "yarn", "dev" ]